# Site settings
title: indeex
email: imisslovelove@live.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/books/" # the subpath of your site, e.g. /blog/
url: "http://indeex.org/books" # the base hostname & protocol for your site
twitter_username: imisslovelove
github_username:  houngkinghsi

# Build settings
markdown: kramdown

paginate: 4

author: houngking

gems: [jekyll-paginate]
